### ISSUE TITLE
No longer working with Auto1111 1.6

### ISSUE THREAD

**Issue by firehawkx** [mix1009/sdwebuiapi#122]
Getting the following error when trying to use this with Auto1111 1.6 version.
It was working with the previous versions.

ERROR :
"RuntimeError: (500, '{"error":"TypeError","detail":"","body":"","errors":"Script.run() missing 1 required positional argument: 'csv_mode'"}')
Traceback (most recent call last):"
